# .github/release.yml
# GitHub μλ™ λ¦΄λ¦¬μ¤ λ…ΈνΈ μ„¤μ •

changelog:
    exclude:
        labels:
            - ignore-for-release
            - duplicate
            - invalid
        authors:
            - dependabot[bot]

    categories:
        - title: π¨ Breaking Changes
          labels:
              - breaking-change
              - major

        - title: β¨ New Features
          labels:
              - enhancement
              - feature
              - minor

        - title: π› Bug Fixes
          labels:
              - bug
              - fix
              - patch

        - title: π“ Documentation
          labels:
              - documentation
              - docs

        - title: π”§ Maintenance
          labels:
              - chore
              - refactor
              - dependencies

        - title: π“¦ Other Changes
          labels:
              - "*"
